const express = require('express');
const pool = require('../db');
const router = express.Router({ mergeParams: true });
const id = (value) => /^\d+$/.test(String(value)) && Number(value) > 0 ? Number(value) : null;

router.get('/', async (req, res) => {
  const leagueId = id(req.params.leagueId); if (!leagueId) return res.status(400).json({ message: 'Invalid league id' });
  try {
    if (!(await pool.query('SELECT 1 FROM league WHERE id=$1', [leagueId])).rowCount) return res.status(404).json({ message: 'League not found' });
    const result = await pool.query(`SELECT t.id,t.league_id AS "leagueId",t.name,t.sort_order AS "sortOrder",COUNT(lm.id)::int AS "memberCount",
      COALESCE(json_agg(json_build_object('memberId',m.id,'name',m.name,'memberType',m.grade) ORDER BY m.name) FILTER (WHERE m.id IS NOT NULL),'[]') AS members
      FROM team t LEFT JOIN league_member lm ON lm.team_id=t.id LEFT JOIN member m ON m.id=lm.member_id
      WHERE t.league_id=$1 GROUP BY t.id ORDER BY t.sort_order,t.id`, [leagueId]);
    res.json(result.rows);
  } catch (e) { console.error(e); res.status(500).json({ message: '서버 오류가 발생했습니다. 잠시 후 다시 시도해주세요.' }); }
});
router.post('/', async (req,res) => { const leagueId=id(req.params.leagueId); const name=String(req.body?.name||'').trim(); if(!leagueId||!name)return res.status(400).json({message:'팀 이름은 필수입니다.'}); try { if(!(await pool.query('SELECT 1 FROM league WHERE id=$1',[leagueId])).rowCount)return res.status(404).json({message:'League not found'}); const r=await pool.query(`INSERT INTO team(league_id,name,sort_order) VALUES($1,$2,COALESCE((SELECT MAX(sort_order)+1 FROM team WHERE league_id=$1),1)) RETURNING id,league_id AS "leagueId",name,sort_order AS "sortOrder"`,[leagueId,name]); res.status(201).json(r.rows[0]); } catch(e){if(e.code==='23505')return res.status(409).json({message:'같은 리그에 동일한 팀명이 있습니다.'}); console.error(e);res.status(500).json({message:'서버 오류가 발생했습니다. 잠시 후 다시 시도해주세요.'});} });
router.patch('/:teamId', async (req,res)=>{const leagueId=id(req.params.leagueId),teamId=id(req.params.teamId),name=String(req.body?.name||'').trim();if(!leagueId||!teamId||!name)return res.status(400).json({message:'유효한 팀 이름이 필요합니다.'});try{const r=await pool.query('UPDATE team SET name=$1 WHERE id=$2 AND league_id=$3 RETURNING id,league_id AS "leagueId",name,sort_order AS "sortOrder"',[name,teamId,leagueId]);if(!r.rowCount)return res.status(404).json({message:'Team not found'});res.json(r.rows[0]);}catch(e){if(e.code==='23505')return res.status(409).json({message:'같은 리그에 동일한 팀명이 있습니다.'});res.status(500).json({message:'서버 오류가 발생했습니다. 잠시 후 다시 시도해주세요.'});}});
router.delete('/:teamId',async(req,res)=>{const leagueId=id(req.params.leagueId),teamId=id(req.params.teamId);if(!leagueId||!teamId)return res.status(400).json({message:'Invalid team id'});try{const t=await pool.query('SELECT 1 FROM team WHERE id=$1 AND league_id=$2',[teamId,leagueId]);if(!t.rowCount)return res.status(404).json({message:'Team not found'});if((await pool.query('SELECT 1 FROM league_member WHERE team_id=$1 LIMIT 1',[teamId])).rowCount)return res.status(409).json({message:'팀에 배정된 참가자가 있어 삭제할 수 없습니다.'});await pool.query('DELETE FROM team WHERE id=$1',[teamId]);res.status(204).send();}catch(e){res.status(500).json({message:'서버 오류가 발생했습니다. 잠시 후 다시 시도해주세요.'});}});
router.put('/assignments',async(req,res)=>{const leagueId=id(req.params.leagueId),assignments=req.body?.assignments;if(!leagueId||!Array.isArray(assignments))return res.status(400).json({message:'assignments must be an array'});if(assignments.some(a=>!Number.isSafeInteger(a.memberId)||a.memberId<=0)||new Set(assignments.map(a=>a.memberId)).size!==assignments.length)return res.status(400).json({message:'중복되거나 유효하지 않은 참가자가 있습니다.'});const client=await pool.connect();try{await client.query('BEGIN');if(!(await client.query('SELECT 1 FROM league WHERE id=$1',[leagueId])).rowCount){await client.query('ROLLBACK');return res.status(404).json({message:'League not found'});}for(const a of assignments){const lm=await client.query('SELECT id FROM league_member WHERE league_id=$1 AND member_id=$2',[leagueId,a.memberId]);if(!lm.rowCount){await client.query('ROLLBACK');return res.status(400).json({message:'해당 리그 참가자가 아닌 회원은 배정할 수 없습니다.'});}if(a.teamId!==null&&!Number.isSafeInteger(a.teamId)){await client.query('ROLLBACK');return res.status(400).json({message:'유효하지 않은 teamId입니다.'});}if(a.teamId!==null&&!(await client.query('SELECT 1 FROM team WHERE id=$1 AND league_id=$2',[a.teamId,leagueId])).rowCount){await client.query('ROLLBACK');return res.status(400).json({message:'다른 리그의 팀에는 배정할 수 없습니다.'});}}for(const a of assignments)await client.query('UPDATE league_member SET team_id=$1 WHERE league_id=$2 AND member_id=$3',[a.teamId,leagueId,a.memberId]);await client.query('COMMIT');res.json({leagueId,assignments});}catch(e){await client.query('ROLLBACK');console.error(e);res.status(500).json({message:'서버 오류가 발생했습니다. 잠시 후 다시 시도해주세요.'});}finally{client.release();}});
module.exports=router;
