import { apiRequest } from './api'
export const getLeagueGames = (id) => apiRequest(`/leagues/${id}/games`)
export const getLeagueAttendanceSummary = id => apiRequest(`/leagues/${id}/attendance/summary`)
export const getLeagueAttendance = (id, date) => apiRequest(`/leagues/${id}/attendance?date=${encodeURIComponent(date)}`)
export const getLeagueAttendanceRates = id => apiRequest(`/leagues/${id}/attendance/rates`)
export const getAdminLeagueGames = (id) => apiRequest(`/admin/leagues/${id}/games`)
export const createAdminGame = (id, data) => apiRequest(`/admin/leagues/${id}/games`, { method: 'POST', body: JSON.stringify(data) })
export const createAdminGameSet = (id, data) => apiRequest(`/admin/leagues/${id}/games/set`, { method: 'POST', body: JSON.stringify(data) })
export const updateAdminGame = (leagueId, gameId, data) => apiRequest(`/admin/leagues/${leagueId}/games/${gameId}`, { method: 'PATCH', body: JSON.stringify(data) })
export const deleteAdminGame = (leagueId, gameId) => apiRequest(`/admin/leagues/${leagueId}/games/${gameId}`, { method: 'DELETE' })
export const getAdminPlayerScores = gameId => apiRequest(`/admin/games/${gameId}/player-scores`)
export const saveAdminPlayerScores = (gameId, scores) => apiRequest(`/admin/games/${gameId}/player-scores`, { method: 'PUT', body: JSON.stringify({ scores }) })
export const getPlayerScores = gameId => apiRequest(`/games/${gameId}/player-scores`)
export const getAdminAttendanceDates = leagueId => apiRequest(`/admin/leagues/${leagueId}/attendance/dates`)
export const getAdminLeagueAttendance = (leagueId, date) => apiRequest(`/admin/leagues/${leagueId}/attendance?date=${encodeURIComponent(date)}`)
export const saveAdminLeagueAttendance = (leagueId, date, attendance) => apiRequest(`/admin/leagues/${leagueId}/attendance/${date}`, { method: 'PUT', body: JSON.stringify({ attendance }) })
