import { apiRequest } from './api'
export const getLeagues = () => apiRequest('/leagues')
export const getLeague = (id) => apiRequest(`/leagues/${id}`)
export const getLeagueStandings = (id) => apiRequest(`/leagues/${id}/standings`)
export const getLeagueScorers = (id) => apiRequest(`/leagues/${id}/scorers`)
export const getLeagueWinner = (id) => apiRequest(`/leagues/${id}/winner`)
export const getLeagueWinImpact = (id) => apiRequest(`/leagues/${id}/win-impact`)
export const getWinningCombinations = (id, admin = false) => apiRequest(`${admin ? '/admin' : ''}/leagues/${id}/winning-combinations?limit=${admin ? 20 : 7}`)
export const getLeagueChampions = () => apiRequest('/leagues/champions')
export const updateLeagueWinner = (leagueId, teamId) => apiRequest(`/admin/leagues/${leagueId}/winner`, { method: 'PATCH', body: JSON.stringify({ teamId }) })
export const createLeague = (data) => apiRequest('/admin/leagues', { method: 'POST', body: JSON.stringify(data) })
