BEGIN;
CREATE TABLE IF NOT EXISTS admin_account (
  id BIGSERIAL PRIMARY KEY, login_id VARCHAR(100) NOT NULL UNIQUE, name VARCHAR(100) NOT NULL,
  password_hash TEXT NOT NULL, role VARCHAR(20) NOT NULL DEFAULT 'ADMIN' CHECK (role IN ('ADMIN','MEMBER')),
  is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS admin_session (
  id BIGSERIAL PRIMARY KEY, admin_account_id BIGINT NOT NULL REFERENCES admin_account(id) ON DELETE CASCADE,
  token_hash CHAR(64) NOT NULL UNIQUE, expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_admin_session_expires_at ON admin_session(expires_at);
COMMIT;
