import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import PageTitle from '../../components/PageTitle'
import { ErrorMessage, EmptyState, Loading } from '../../components/Status'
import { getLeague } from '../../services/leagueApi'
import { getLeagueParticipants } from '../../services/participantApi'
import { getLeagueTeams } from '../../services/teamApi'
import { getLeagueGames, getPlayerScores } from '../../services/gameApi'
import '../../styles/game-list.css'

const tabs = [['standings', '순위'], ['games', '경기'], ['participants', '참가자'], ['winner', '우승팀']]
const formatDate = value => value ? new Date(`${String(value).slice(0, 10)}T00:00:00`).toLocaleDateString('ko-KR', { month: 'long', day: 'numeric' }) : '날짜 미정'

export default function LeagueDetailPage() {
  const { id } = useParams(); const [league, setLeague] = useState(null); const [participants, setParticipants] = useState(null); const [teams, setTeams] = useState([]); const [games, setGames] = useState(null); const [scores, setScores] = useState({}); const [tab, setTab] = useState('standings'); const [error, setError] = useState('')
  useEffect(() => { getLeague(id).then(setLeague).catch(() => setError('정보를 불러오지 못했습니다.')) }, [id])
  useEffect(() => { if (tab === 'participants') Promise.all([getLeagueParticipants(id), getLeagueTeams(id)]).then(([p, t]) => { setParticipants(p); setTeams(t) }).catch(() => setError('참가자 정보를 불러오지 못했습니다.')); if (tab === 'games') getLeagueGames(id).then(setGames).catch(() => setError('경기 정보를 불러오지 못했습니다.')) }, [id, tab])
  const grouped = teams.map(t => ({ ...t, members: participants?.filter(p => Number(p.teamId) === Number(t.id)) || [] })); const unassigned = participants?.filter(p => !p.teamId) || []
  const showScores = gameId => { if (scores[gameId] !== undefined) return; getPlayerScores(gameId).then(data => setScores(s => ({ ...s, [gameId]: data }))).catch(() => setScores(s => ({ ...s, [gameId]: null }))) }
  if (error) return <><PageTitle title="리그 상세" back /><ErrorMessage text={error} /></>; if (!league) return <><PageTitle title="리그 상세" back /><Loading /></>
  return <><PageTitle eyebrow="LEAGUE DETAIL" title={league.name} back /><div className="details card"><div className="row"><span>연도</span><b>{league.year}년</b></div><div className="row"><span>분기</span><b>{league.quarter}분기</b></div><div className="row"><span>상태</span><b>{league.status}</b></div></div><div className="tabs">{tabs.map(([key, label]) => <button className={tab === key ? 'selected' : ''} key={key} onClick={() => setTab(key)}>{label}</button>)}</div>{tab === 'games' ? games === null ? <Loading /> : games.length === 0 ? <EmptyState text="등록된 경기가 없습니다." /> : <div className="game-list">{games.map(game => { const expanded = scores[game.gameId]; return <article className="card game-card" key={game.gameId}><div className="game-card-head"><b>{game.gameNo}경기</b><span className="game-status">{game.status === 'COMPLETED' ? '종료' : '예정'}</span></div><div className="game-match"><strong title={game.homeTeam.name}>{game.homeTeam.name}</strong><b className={game.status === 'COMPLETED' ? 'game-score' : 'game-vs'}>{game.status === 'COMPLETED' ? `${game.homeScore} : ${game.awayScore}` : 'VS'}</b><strong title={game.awayTeam.name}>{game.awayTeam.name}</strong></div><div className="game-date">{formatDate(game.gameDate)}</div>{game.status === 'COMPLETED' && <button className="score-toggle" onClick={() => showScores(game.gameId)}>개인 득점 보기 {expanded ? '▲' : '〉'}</button>}{expanded && <div className="score-details">{expanded.teams.map(team => <div className="score-team" key={team.teamId}><h4>{team.teamName}</h4>{team.players.filter(p => p.hasScore).map(p => <p key={p.leagueMemberId}><b>{p.name}</b><span>{p.points}점</span></p>)}{team.players.every(p => !p.hasScore) && <p className="muted">개인 득점 기록이 아직 입력되지 않았습니다.</p>}</div>)}</div>}</article> })}</div> : tab === 'participants' ? participants === null ? <Loading /> : <div className="team-groups">{grouped.map(t => <section className="card team-group" key={t.id}><h3>{t.name}</h3>{t.members.map(m => <p key={m.memberId}><b>{m.name}</b><span>{m.memberType === 'REGULAR' ? '정회원' : '게스트'}</span></p>)}</section>)}{unassigned.length > 0 && <section className="card team-group"><h3>미배정</h3>{unassigned.map(m => <p key={m.memberId}>{m.name}</p>)}</section>}</div> : <div className="empty card"><h3>아직 관련 정보가 없습니다.</h3></div>}</>
}
