import { BrowserRouter, Navigate, Route, Routes } from 'react-router-dom'
import AppLayout from './components/AppLayout'
import HomePage from './pages/HomePage'
import LeagueListPage from './pages/leagues/LeagueListPage'
import LeagueDetailPage from './pages/leagues/LeagueDetailPage'
import MemberListPage from './pages/members/MemberListPage'
import MemberDetailPage from './pages/members/MemberDetailPage'
import AdminHomePage from './pages/admin/AdminHomePage'
import AdminMemberListPage from './pages/admin/AdminMemberListPage'
import AdminMemberDetailPage from './pages/admin/AdminMemberDetailPage'
import AdminMemberCreatePage from './pages/admin/AdminMemberCreatePage'
import AdminLeagueListPage from './pages/admin/AdminLeagueListPage'
import AdminLeagueCreatePage from './pages/admin/AdminLeagueCreatePage'
import AdminParticipantsPage from './pages/admin/AdminParticipantsPage'
import ComingSoonPage from './pages/admin/ComingSoonPage'
import './App.css'
import './styles/router.css'

export default function App() { return <BrowserRouter><Routes><Route element={<AppLayout />}><Route path="/" element={<HomePage />} /><Route path="/leagues" element={<LeagueListPage />} /><Route path="/leagues/:id" element={<LeagueDetailPage />} /><Route path="/members" element={<MemberListPage />} /><Route path="/members/:id" element={<MemberDetailPage />} /><Route path="/admin" element={<AdminHomePage />} /><Route path="/admin/members" element={<AdminMemberListPage />} /><Route path="/admin/members/new" element={<AdminMemberCreatePage />} /><Route path="/admin/members/:id" element={<AdminMemberDetailPage />} /><Route path="/admin/leagues" element={<AdminLeagueListPage />} /><Route path="/admin/leagues/new" element={<AdminLeagueCreatePage />} /><Route path="/admin/participants" element={<AdminParticipantsPage />} /><Route path="/admin/teams" element={<ComingSoonPage title="팀 관리" />} /><Route path="/admin/games" element={<ComingSoonPage title="경기 관리" />} /><Route path="/admin/attendance" element={<ComingSoonPage title="출석 관리" />} /><Route path="/admin/champions" element={<ComingSoonPage title="우승팀 관리" />} /><Route path="*" element={<Navigate to="/" replace />} /></Route></Routes></BrowserRouter> }
