import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import PageTitle from '../../components/PageTitle'
import { ErrorMessage, Loading } from '../../components/Status'
import { getAdminMember, updateAdminMember, updateAdminMemberNote } from '../../services/memberApi'

export default function AdminMemberDetailPage() {
  const { id } = useParams(); const [member, setMember] = useState(null); const [name, setName] = useState(''); const [birthYear, setBirthYear] = useState(''); const [memberType, setMemberType] = useState('REGULAR'); const [note, setNote] = useState(''); const [editing, setEditing] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  useEffect(() => { getAdminMember(id).then((data) => { setMember(data); setName(data.name); setBirthYear(data.birthYear == null ? '' : String(data.birthYear)); setMemberType(data.memberType); setNote(data.note || '') }).catch(() => setError('정보를 불러오지 못했습니다.')) }, [id])
  async function saveInfo(event) { event.preventDefault(); setSaving(true); try { const data = await updateAdminMember(id, { name, birthYear: birthYear === '' ? null : Number(birthYear), member_type: memberType, active: member.isActive }); setMember(data); setEditing(false); setMessage('회원정보를 저장했습니다.'); setError('') } catch (e) { setError(e.message || '회원정보를 저장하지 못했습니다.') } finally { setSaving(false) } }
  async function saveNote(event) { event.preventDefault(); setSaving(true); try { const data = await updateAdminMemberNote(id, note); setNote(data.note || ''); setMessage('비고를 저장했습니다.'); setError('') } catch { setError('비고를 저장하지 못했습니다.') } finally { setSaving(false) } }
  async function toggleActive() { setSaving(true); try { const data = await updateAdminMember(id, { active: !member.isActive }); setMember(data); setMessage(data.isActive ? '회원을 다시 활성화했습니다.' : '회원을 비활성화했습니다.'); setError('') } catch { setError('회원 상태를 변경하지 못했습니다.') } finally { setSaving(false) } }
  return <><PageTitle eyebrow="MEMBER DETAIL" title={member?.name || '회원 상세'} back />{error && <ErrorMessage text={error} />}{!member && !error ? <Loading /> : member && <><div className="member-detail-head"><span className={member.isActive ? 'active-pill' : 'inactive-pill'}>{member.isActive ? '활성 회원' : '비활성 회원'}</span><button className="secondary small-button" onClick={() => setEditing(!editing)}>{editing ? '편집 취소' : '회원정보 수정'}</button></div>{editing ? <form className="form card" onSubmit={saveInfo}><label htmlFor="edit-name">이름</label><input id="edit-name" value={name} onChange={(e) => setName(e.target.value)} required /><label htmlFor="edit-birth-year">출생년도</label><input id="edit-birth-year" type="number" inputMode="numeric" min="1900" max={new Date().getFullYear()} value={birthYear} onChange={(e) => setBirthYear(e.target.value)} placeholder="선택 입력" /><label htmlFor="edit-type">회원 구분</label><select id="edit-type" value={memberType} onChange={(e) => setMemberType(e.target.value)}><option value="REGULAR">정회원</option><option value="GUEST">게스트</option></select><button className="primary full" disabled={saving}>{saving ? '저장 중...' : '회원정보 저장'}</button></form> : <div className="details card"><div className="row"><span>이름</span><b>{member.name}</b></div><div className="row"><span>출생년도</span><b>{member.birthYear == null ? '미등록' : `${member.birthYear}년`}</b></div><div className="row"><span>회원등급</span><b>{member.memberType === 'REGULAR' ? '정회원' : '게스트'}</b></div><div className="row"><span>상태</span><b>{member.isActive ? '활성' : '비활성'}</b></div></div>}<form className="form card" onSubmit={saveNote}><label htmlFor="note">관리자 비고</label><textarea id="note" rows="4" value={note} onChange={(e) => setNote(e.target.value)} placeholder="관리자만 확인할 수 있는 메모" /><button className="primary full" disabled={saving}>{saving ? '저장 중...' : '비고 저장'}</button></form><button className="secondary full" onClick={toggleActive} disabled={saving}>{member.isActive ? '회원 비활성화' : '회원 다시 활성화'}</button>{message && <p className="success">{message}</p>}</>}</>
}
