import { useEffect, useState } from 'react'
import PageTitle from '../../components/PageTitle'
import { ErrorMessage, Loading } from '../../components/Status'
import { getLeagues } from '../../services/leagueApi'
import { getAdminLeagueTeams } from '../../services/teamApi'
import { createAdminGame, deleteAdminGame, getAdminLeagueGames, updateAdminGame } from '../../services/gameApi'

const blank = { homeTeamId: '', awayTeamId: '', scheduledAt: '', status: 'SCHEDULED', homeScore: '', awayScore: '' }
const localDate = value => value ? new Date(value).toISOString().slice(0, 16) : ''

export default function AdminGamesPage() {
  const [leagues, setLeagues] = useState([]), [leagueId, setLeagueId] = useState(''), [teams, setTeams] = useState([]), [games, setGames] = useState(null), [form, setForm] = useState(blank), [editing, setEditing] = useState(null), [error, setError] = useState(''), [message, setMessage] = useState('')
  async function load() { try { const [g, t] = await Promise.all([getAdminLeagueGames(leagueId), getAdminLeagueTeams(leagueId)]); setGames(g); setTeams(t) } catch (e) { setError(e.message) } }
  useEffect(() => { getLeagues().then(data => { setLeagues(data); if (data[0]) setLeagueId(String(data[0].id)) }).catch(e => setError(e.message)) }, [])
  useEffect(() => { if (leagueId) { setGames(null); load() } }, [leagueId])
  const change = (key, value) => setForm(current => ({ ...current, [key]: value }))
  const edit = game => { setEditing(game.gameId); setForm({ homeTeamId: String(game.homeTeamId), awayTeamId: String(game.awayTeamId), scheduledAt: localDate(game.scheduledAt), status: game.status, homeScore: game.homeScore ?? '', awayScore: game.awayScore ?? '' }) }
  const reset = () => { setEditing(null); setForm(blank) }
  async function save(event) { event.preventDefault(); setError(''); const data = { ...form, homeTeamId: Number(form.homeTeamId), awayTeamId: Number(form.awayTeamId), scheduledAt: form.scheduledAt ? new Date(form.scheduledAt).toISOString() : null, homeScore: form.status === 'COMPLETED' ? Number(form.homeScore) : null, awayScore: form.status === 'COMPLETED' ? Number(form.awayScore) : null }; try { if (editing) await updateAdminGame(leagueId, editing, data); else await createAdminGame(leagueId, data); setMessage(editing ? '경기를 수정했습니다.' : '경기를 추가했습니다.'); reset(); load() } catch (e) { setError(e.message) } }
  async function remove(game) { if (!window.confirm('이 경기를 삭제할까요?')) return; try { await deleteAdminGame(leagueId, game.gameId); setMessage('경기를 삭제했습니다.'); load() } catch (e) { setError(e.message) } }
  return <><PageTitle eyebrow="ADMIN · GAMES" title="경기 관리" description="리그별 대진과 경기 결과를 관리하세요." back />{error && <ErrorMessage text={error} />}<select className="league-select" value={leagueId} onChange={e => setLeagueId(e.target.value)}>{leagues.map(l => <option key={l.id} value={l.id}>{l.name}</option>)}</select><form className="card form" onSubmit={save}><h3>{editing ? '경기 수정' : '경기 추가'}</h3><label>홈팀<select value={form.homeTeamId} onChange={e => change('homeTeamId', e.target.value)} required><option value="">선택</option>{teams.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>원정팀<select value={form.awayTeamId} onChange={e => change('awayTeamId', e.target.value)} required><option value="">선택</option>{teams.filter(t => String(t.id) !== String(form.homeTeamId)).map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>경기 일시<input type="datetime-local" value={form.scheduledAt} onChange={e => change('scheduledAt', e.target.value)} /></label><label>상태<select value={form.status} onChange={e => change('status', e.target.value)}><option value="SCHEDULED">예정</option><option value="COMPLETED">종료</option></select></label>{form.status === 'COMPLETED' && <div className="score-fields"><label>홈팀 점수<input type="number" min="0" value={form.homeScore} onChange={e => change('homeScore', e.target.value)} required /></label><label>원정팀 점수<input type="number" min="0" value={form.awayScore} onChange={e => change('awayScore', e.target.value)} required /></label></div>}<button className="primary" disabled={!teams.length}>{editing ? '수정 저장' : '경기 추가'}</button>{editing && <button type="button" className="secondary" onClick={reset}>취소</button>}</form>{message && <p className="success">{message}</p>}{games === null ? <Loading /> : games.length === 0 ? <div className="empty card"><h3>등록된 경기가 없습니다.</h3></div> : <div className="game-list">{games.map(game => <article className="card game-card" key={game.gameId}><div className="game-card-head"><span>{game.status === 'COMPLETED' ? '경기 종료' : '경기 예정'}</span><small>{game.scheduledAt ? new Date(game.scheduledAt).toLocaleString('ko-KR') : '일시 미정'}</small></div><h3>{game.homeTeamName} {game.status === 'COMPLETED' ? `${game.homeScore} : ${game.awayScore}` : 'vs'} {game.awayTeamName}</h3><button className="secondary small-button" onClick={() => edit(game)}>수정</button> <button className="secondary small-button" onClick={() => remove(game)}>삭제</button></article>)}</div>}</>
}
